// src/constants/enums.js
export const EMPLOYMENT_TYPES = ["FULL-TIME", "CONTRACT", "INTERNSHIP"];

export const DEPARTMENTS = [
  "ACADEMIC",
  "ADMINISTRATION",
  "LABORATORY",
  "ACCOUNTS",
  "MARKETING",
  "HUMAN RESOURCES",
  "OPERATIONS",
];

export const GRADES = ["JUNIOR", "SENIOR", "LEAD", "HEAD"];

export const ROLES = [
  "PRINCIPAL",
  "VICE PRINCIPAL",
  "HEAD OF DEPARTMENT",
  "SENIOR TEACHER",
  "JUNIOR TEACHER",
  "ASSISTANT TEACHER",
  "LABORATORY ASSISTANT",
  "HR MANAGER",
  "ADMIN LEAD",
  "MARKETING MANAGER",
  "COORDINATOR",
  "ACCOUNTANT",
  "CARETAKER",
];

export const CLASS_SCOPES = [
  "PRE-PRIMARY",
  "PRIMARY",
  "SECONDARY",
  "HIGHER SECONDARY",
];

export const MEDIUMS = ["ENGLISH", "BENGALI", "HINDI", "OTHERS"];

export const BOARDS = ["CBSE", "ICSE", "ISC", "WBBSE", "WBCHSE", "OTHER"];

export const SUBJECTS = [
  "ENGLISH",
  "MATHEMATICS",
  "SCIENCE",
  "PHYSICS",
  "CHEMISTRY",
  "BIOLOGY",
  "COMPUTER SCIENCE",
  "HISTORY",
  "GEOGRAPHY",
  "ECONOMICS",
  "BUSINESS STUDIES",
  "ACCOUNTANCY",
  "PHYSICAL EDUCATION",
];

export const CATEGORIES = [
  "GENERAL",
  "OBC-A",
  "OBC-B",
  "SC",
  "ST",
  "EWS",
  "PWD",
];

export const JOB_STATUS = ["DRAFT", "OPEN", "CLOSED"];
